apiVersion: v1
kind: Service
metadata:
  name: eshop-dev
  namespace: eshop-dev
spec:
  ports:
    - name: https
      targetPort: http
      port: 8443
      protocol: TCP 
  selector:
    run: eshop-dev
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-dev
  namespace: eshop-dev
spec:
  selector:
    matchLabels:
      run: eshop-dev
  replicas: 1
  template:
    metadata:
      labels:
        run: eshop-dev
    spec:
      containers:
      - name: eshop-dev
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-dev-ui
  namespace: eshop-dev
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: eshop-dev
    app.kubernetes.io/name: eshop-dev-ui
spec:
  rules:
  - host: dev.telia-fi-spock.telia.io
    http:
      paths:
      - backend:
          service:
            name: eshop-dev
            port: 
                number: 8443
        path: /eshop-dev
        pathType: Prefix
  tls:
  - hosts:
    - dev.telia-fi-spock.telia.io
    secretName: externaluicerts